jobs:
  - name: build-u14
    type: runSh
    steps:
      - IN: u14-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14-repo/gitRepo/build.sh
      - OUT: u14-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14all
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14all-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14all-repo/gitRepo/build.sh
      - OUT: u14all-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14cpp
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14cpp-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14cpp-repo/gitRepo/build.sh
      - OUT: u14cpp-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14jav
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14jav-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14jav-repo/gitRepo/build.sh
      - OUT: u14jav-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14nod
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14nod-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14nod-repo/gitRepo/build.sh
      - OUT: u14nod-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14pyt
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14pyt-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14pyt-repo/gitRepo/build.sh
      - OUT: u14pyt-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('
