jobs:
  - name: build-u14
    type: runSh
    steps:
      - IN: u14-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14-repo/gitRepo/build.sh
      - OUT: u14-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14all
    type: runSh
    steps:
      - IN: u14-img
      - IN: u14all-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14all-repo/gitRepo/build.sh
      - OUT: u14all-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14nodall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14nodall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14nodall-repo/gitRepo/build.sh
      - OUT: u14nodall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14pytall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14pytall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14pytall-repo/gitRepo/build.sh
      - OUT: u14pytall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14cloall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14cloall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14cloall-repo/gitRepo/build.sh
      - OUT: u14cloall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14golall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14golall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14golall-repo/gitRepo/build.sh
      - OUT: u14golall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14javall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14javall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14javall-repo/gitRepo/build.sh
      - OUT: u14javall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14scaall
    type: runSh
    steps:
      - IN: u14javall-img
      - IN: u14scaall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14scaall-repo/gitRepo/build.sh
      - OUT: u14scaall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14ruball
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14ruball-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14ruball-repo/gitRepo/build.sh
      - OUT: u14ruball-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14phpall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14phpall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14phpall-repo/gitRepo/build.sh
      - OUT: u14phpall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u14cppall
    type: runSh
    steps:
      - IN: u14all-img
      - IN: u14cppall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u14cppall-repo/gitRepo/build.sh
      - OUT: u14cppall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16
    type: runSh
    steps:
      - IN: u16-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16-repo/gitRepo/build.sh
      - OUT: u16-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16all
    type: runSh
    steps:
      - IN: u16-img
      - IN: u16all-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16all-repo/gitRepo/build.sh
      - OUT: u16all-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16nodall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16nodall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16nodall-repo/gitRepo/build.sh
      - OUT: u16nodall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16pytall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16pytall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16pytall-repo/gitRepo/build.sh
      - OUT: u16pytall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16cloall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16cloall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16cloall-repo/gitRepo/build.sh
      - OUT: u16cloall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16golall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16golall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16golall-repo/gitRepo/build.sh
      - OUT: u16golall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16javall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16javall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16javall-repo/gitRepo/build.sh
      - OUT: u16javall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16scaall
    type: runSh
    steps:
      - IN: u16javall-img
      - IN: u16scaall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16scaall-repo/gitRepo/build.sh
      - OUT: u16scaall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16ruball
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16ruball-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16ruball-repo/gitRepo/build.sh
      - OUT: u16ruball-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16phpall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16phpall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16phpall-repo/gitRepo/build.sh
      - OUT: u16phpall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('

  - name: build-u16cppall
    type: runSh
    steps:
      - IN: u16all-img
      - IN: u16cppall-repo
      - IN: docker-creds
      - TASK:
        - script: sudo apt-get install -y jq
        - script: ./IN/u16cppall-repo/gitRepo/build.sh
      - OUT: u16cppall-img
    on_success:
      - echo 'on success !!!!!'
    on_failure:
      - echo 'Failed job .... :('
